<?php

namespace AppBundle\Repository;

/**
 * CarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarreraRepository extends \Doctrine\ORM\EntityRepository
{
}
