<?php

namespace AppBundle\Repository;

/**
 * CuatrimestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuatrimestreRepository extends \Doctrine\ORM\EntityRepository
{
}
