<?php

namespace AppBundle\Repository;

/**
 * MateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaRepository extends \Doctrine\ORM\EntityRepository
{
}
