<?php

namespace AppBundle\Repository;

/**
 * RespuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
