app:
    resource: '@AppBundle/Controller/'
    type: annotation

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

materias:
    type: rest
    resource: AppBundle\Controller\MateriaController

cuatrimestre:
    type: rest
    resource: AppBundle\Controller\CuatrimestreController

comision:
    type: rest
    resource: AppBundle\Controller\ComisionController

oferta:
    type: rest
    resource: AppBundle\Controller\OfertaController

alumno:
    type: rest
    resource: AppBundle\Controller\AlumnoController
